name: Build and test

on:
  # Run on pushes to main
  push:
    branches:
      - main
  # And all pull requests
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # Cancels jobs running if new commits are pushed
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build and test implicit fluids"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The docker container to use.
    container:
      image: firedrakeproject/firedrake-vanilla-default:latest
    # Steps represent a sequence of tasks that will be executed as
    # part of the jobs
    steps:
      - uses: actions/checkout@v6
        with:
          path: repo

      - name: Create virtual environment
        # pass '--system-site-packages' so Firedrake can be found
        run: python3 -m venv --system-site-packages venv

      - name: Install package
        run: |
          . venv/bin/activate
          python -m pip install './repo[lint,test]'

      - name: Install irksome and pandas
        run: |
          . venv/bin/activate
          python -m pip install git+https://github.com/firedrakeproject/irksome.git
          python -m pip install pandas
          python -m pip list

      - name: Run lint
        run: |
          . venv/bin/activate
          python -m flake8 ./repo

      - name: Run tests
        run: |
          . venv/bin/activate
          python -m pytest -v -n 6 --durations=40 --timeout=600 --cov=./repo/implicit_fluids --cov-report=term ./repo/tests/
